### ISSUE TITLE
Do I should inform the maintainer of the repository to add here?

### ISSUE THREAD

**Issue by eltonjncorreia** [OtacilioN/awesome-hacktoberfest-2018#22]

**Comment by OtacilioN** [comment]
Nope! You just need to add the repository to the list!

You can check our [Code of Conduct](https://github.com/OtacilioN/awesome-hacktoberfest-2018/blob/master/CODE_OF_CONDUCT.md) here!

**Comment by eltonjncorreia** [comment]
Ok! Thanks!

**Comment by OtacilioN** [comment]
Welcome my friend! It is awesome to find another Brazilian here!
