### ISSUE TITLE
Fix [Beetlesbot] (https://github.com/bleeptrack/beetlesbot/) in README.md

### ISSUE THREAD

**Issue by OtacilioN** [OtacilioN/awesome-hacktoberfest-2018#36]
Remove the whitespace between [Beetlesbot] and the link (https://github.com/bleeptrack/beetlesbot/)
enjoy that you've solved the bug, and add one more project to the list!

**Comment by pheliperocha** [comment]
Can I get this?

**Comment by OtacilioN** [comment]
Yes! Go forward @pheliperocha !

**Comment by OtacilioN** [comment]
Awesome, thanks for contributing!
